APPNAME = 'Growbies'
USERNAME = APPNAME.lower()
GROUPNAME = APPNAME.lower()
UINT8_MAX = 0xFF
UINT16_MAX = 0xFFFF
INT32_MAX = 0x7FFFFFFF
YAML_INDENT = 2
DEFAULT_CMD_TIMEOUT_SECONDS = 10
TABLE_COLUMN_WIDTH = 30

# DB
RDBMS_SERVICE = 'postgresql'
DB_NAME = APPNAME.lower()
DB_USER = APPNAME.lower()
ADMIN_DB_USER = 'postgres'
SQLMODEL_ADDRESS_FMT = f'postgresql+psycopg2://{DB_USER}@{{address}}/{DB_NAME}'
