clean:
	platformio run -t clean

mini:
	platformio run --environment mini

upload-mini:
	platformio run -t upload -e mini

uno:
	platformio run --environment uno

upload-uno:
	platformio run -t upload -e uno
