FROM debian:latest

# Install generic build dependencies
RUN \
    apt update -y && \
    apt install dh-make -y && \
    apt install debmake -y && \
    apt install build-essential -y && \
    apt install -y systemd

ARG PATH_CODE="/code"
WORKDIR ${PATH_CODE}
ENV PATH_SRC=debian/src
ENV PATHS_ENV=${PATH_SRC}/build/paths.env

RUN \
    # Install package specific build dependencies
    apt-get build-dep -y . && \
    # Build the package
    debuild --preserve-env -b --no-sign --lintian-opts --allow-root && \
    apt install -y /growbies*.deb && \
    systemctl enable growbies

CMD [ "/usr/lib/systemd/systemd" ]
