FROM debian:latest

# Install generic build dependencies
RUN \
    apt update -y && \
    apt install dh-make -y && \
    apt install debmake -y && \
    apt install build-essential -y && \
    apt install -y systemd

ARG CWD=/code
WORKDIR ${CWD}
ENV REL_PATH_SRC=debian/src
ENV PATH_SRC=${CWD}/${REL_PATH_SRC}

ENV PATHS_ENV=${PATH_SRC}/build/paths.env

COPY . .

RUN \
    # Install package specific build dependencies
    apt-get build-dep -y . && \
    # Build the package
    debuild --preserve-env -b --no-sign --lintian-opts --allow-root && \
    apt install /growbies*.deb

CMD [ "/usr/lib/systemd/systemd" ]
