#!/bin/bash

set -e

source /usr/lib/growbies/paths.env

# Install into a python virtual environment
${PATH_DEBIAN_BASE_PYTHON} -m venv "${PATH_USR_LIB_GROWBIES_VENV}"
source "${PATH_USR_LIB_GROWBIES_VENV_ACTIVATE}"
pip install "${PATH_USR_LIB_GROWBIES}"/*.whl --force-reinstall
rm "${PATH_USR_LIB_GROWBIES}"/*.whl
