#!/bin/bash

set -e

source /usr/lib/growbies/paths.env

# Install into a python virtual environment
${PATH_DEBIAN_BASE_PYTHON} -m venv "${PATH_USR_LIB_GROWBIES_VENV}"
source "${PATH_USR_LIB_GROWBIES_VENV_ACTIVATE}"
pip install "${PATH_USR_LIB_GROWBIES}"/*.whl --force-reinstall
rm "${PATH_USR_LIB_GROWBIES}"/*.whl

# If the application user doesn't exist
if ! id -u "${PATH_APPNAME}" >/dev/null 2>&1; then
  # Add a system user/group that the application will be ran as
  useradd "${PATH_APPNAME}" --system --no-create-home --shell /bin/bash
fi
# Add the newly created user to the dialout group for serial port access
usermod -aG dialout "${PATH_APPNAME}"
# Make application user the owner of the pertinent application paths
chown -R "${PATH_APPNAME}":"${PATH_APPNAME}" \
  "${PATH_USR_LIB_GROWBIES}" "${PATH_VAR_LIB_GROWBIES}" "${PATH_VAR_LOG_GROWBIES}" \
  "${PATH_ETC_GROWBIES}"

## Create a default configuration file if necessary.
python -m growbies.cfg init --yes

# Enable the service so that it will start with system boot.
systemctl enable "${PATH_APPNAME}"
# If the system has been booted
if systemd-notify --booted; then
  # Start or restart the application.
  systemctl restart "${PATH_APPNAME}"
fi

