#!/bin/bash

set -e

path_to_install_vars="${DESTDIR}/usr/lib/growbies-gateway/install_vars.sh"

source "${path_to_install_vars}"
${PYTHON} -m venv "${PATH_OUT_VENV}"
source "${PATH_OUT_VENV_ACTIVATE}"
pip install "${PATH_OUT_LIB}"/*.whl
