#!/bin/bash

source /usr/lib/growbies/venv/bin/activate

case "$1" in
    start_service)
      python -m growbies service start
      ;;
    stop_service)
      python -m growbies service stop
      ;;
esac
