clean:
	platformio run -t clean

esp32c3:
	platformio run --environment esp32c3

upload-esp32c3:
	platformio run -t upload -e esp32c3

mini:
	platformio run --environment mini

upload-mini:
	platformio run -t upload -e mini

uno:
	platformio run --environment uno

upload-uno:
	platformio run -t upload -e uno
